services:
    postgres:
        container_name: postgres
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
           - postgres:/var/lib/postgresql/data
    
    backend:
        depends_on:
            - postgres
        container_name: spring-app
        image: spring-backend:latest
        ports:
            - 9001:9001
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9001/v1"]
            interval: 30s
            timeout: 10s
            retries: 3

    frontend:
        depends_on:
            - postgres
            - backend
        container_name: frontend-app
        image: react-frontend:latest
        ports:
            - 3000:80
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    postgres:
        name: postgres-volume
