name: Buid and Push docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-n-run:
    runs-on: self-hosted
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4
      
      - name: Build frontend
        run: docker build -t react-frontend:latest -f Dockerfile.frontend .

      - name: Build backend
        run: docker build -t spring-backend:latest -f Dockerfile.backend .

      - name: Start the service using docker-compose up
        run: docker compose -f docker-compose.yml up -d
